config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'customers#index'

  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validates :cust_id, presence: true
	validates :name, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  def index
    @customers = Customer.all
    @customers = Customer.where(updated_at: 24.hours.ago..Time.now)
  end

  def new
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.new(customer_params)
  	respond_to do |format|
  		if @customer.save
  			format.html { redirect_to @customer, notice: "User created successfully" }
  			format.json { render json: @customer, status: :created, location: @customer }
  		else
  			format.html { render action: 'new' }
  			format.json { render json: @customer.errors, status: :unprocessable_entity }
  		end
  	end
  end


  def show
  	@customer = Customer.find(params[:id])
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def update
  	@customer = Customer.find(params[:id])
  	respond_to do |format|
	  	if @customer.update(customer_params)
	  		format.html { redirect_to @customer, notice: 'user was successfully updated.'}
	  		format.json { render json: @customer, status: :created, location: @customer }
	  	else
	  		format.html { render action: "update" }
	  		format.json {render json: @customer.errors, status: :unprocessable_entity}
	  	 end
  	end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end
  
  private
  def customer_params
  	params.require(:customer).permit(:cust_id, :name, :description, :created_at, :updated_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
  <% if @customer.errors.any? %>
	<div id='error_explanation'>
		<h1><%= (pluralize@customer.errors.count, "error") %> Prohibited this event from being saved:</h1>

		<ul>
			<% @customer.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
		</ul>
	</div>
  <% end %>

	<p>
		<%= f.label :UserId %>
		<%= f.text_field :cust_id %>
	</p>

	<p> 
		<%= f.label :UserName %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :Description %>
		<%= f.text_field :description %>
	</p>

	<p>
		<%= f.submit %>
</p>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/customers/index.html.erb
<h1>User Listing </h1>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
table#t01 {
    width: 100%;    
    background-color: #f1f1c1;
}
</style>
<table style="width:100%">
<tr>
<th>UserId</th>
<th>Username</th>
<th>Description</th>
<th>Created_At</th>
<th>Updated_At</th>
</tr>
<% @customers.each do |customer| %>

<tr>
	<td><%= customer.cust_id %></td>
	<td><%= customer.name %></td>
	<td><%= customer.description %></td>
    <td><%= customer.created_at %></td>
    <td><%= customer.updated_at %></td>
	<td><%= link_to 'edit', edit_customer_path(customer) %></td>
	<td><%= link_to "delete", customer_path(customer), :method => :delete,
                                  data: { confirm: "You sure?" } %></td>    
</tr>
<% end %>
</table>
<br>
<%= button_to "New User", new_customer_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get %>

app/views/customers/new.html.erb
<h1>Create New User</h1>
<%= render 'form' %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>
<p>
<strong>UserId</strong>
<%= @customer.cust_id %>
</p>

<p>
<strong>Username</strong>
<%= @customer.name %>
</p>

<p>
<strong>Description</strong>
<%= @customer.description %>
</p>

<%= button_to "Back", customers_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
        <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
         <li><%= button_to "Sign Out", destroy_user_session_path,  method: 'delete', :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip"%></li>
          <% else %>
         <li>
         <li><%= button_to "SIGN IN", new_user_session_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get %></li> 
         </ul>
         <% end %>

<%= yield %>

</body>
</html>